# reliablemask.py
from . import cp
from . import cupy_ndimage


def gradient_amplitude(volume: cp.ndarray) -> cp.ndarray:
    """
    Compute gradient amplitude of a 2D/3D image.
    volume: shape = (X,Y) or (X,Y,Z)
    """
    if volume.ndim == 2:  # 2D
        gx = cupy_ndimage.sobel(volume, axis=0)
        gy = cupy_ndimage.sobel(volume, axis=1)
        return cp.sqrt(gx**2 + gy**2)
    elif volume.ndim == 3:  # 3D
        gx = cupy_ndimage.sobel(volume, axis=0)
        gy = cupy_ndimage.sobel(volume, axis=1)
        gz = cupy_ndimage.sobel(volume, axis=2)
        return cp.sqrt(gx**2 + gy**2 + gz**2)
    else:
        raise ValueError("Only 2D or 3D data are supported")


def compute_spatial_mask(
    mem_dir: str,
    ca_dir: str,
    ref_dir: str,
    option: dict,
    compute_cor_fn,
    read_reg_tiff,
    write_volume_as_ome_tiff,
    configPath: str,
    out_dir: str,
    T: int,
):
    """
    Compute a spatial mask based on membrane / calcium / reference signals.

    This function builds a spatial template by sampling a number of frames
    uniformly across the full time series. The template is generated by averaging
    correlation volumes computed from (membrane, calcium) pairs. The spatial mask
    is then derived by combining:
        - intensity-based masking (low-intensity structures),
        - gradient-structure-based masking (low spatial gradients).

    The final mask is saved as a single-frame OME-TIFF volume.

    Parameters
    ----------
    mem_dir : str
        Path to the registered membrane data directory.
    ca_dir : str
        Path to the registered calcium data directory.
    ref_dir : str
        Path to the registered reference data directory.
    option : dict
        Dictionary containing parameters:
            'sigma': int
                Smoothing scale for gradient-based features.
            'spatialMaskThres': float
                Threshold for the standardized gradient field (Iz_sm).
    compute_cor_fn : callable
        User-provided function that computes correlation:
            cor = compute_cor_fn(mem, ca)
        where the output shape must be (Z, Y, X).
    read_reg_tiff : callable
        Function for reading one frame:
            vol = read_reg_tiff(dir, frame_index, channel)
        Must return a CuPy array with shape (Z, Y, X).
    write_volume_as_ome_tiff : callable
        Function for writing a 3D volume into an OME-TIFF file.
    configPath : str
        Path to the pipeline configuration file.
    out_dir : str
        Directory to store the output spatial mask.
    T : int
        Total number of frames in the dataset.

    Returns
    -------
    spatialMask : cupy.ndarray, dtype=bool, shape=(Z, Y, X)
        The computed spatial mask.
    """
      
    print("Pass 1: building spatial template")

    n_template = min(20, T)
    frames = [int(T * (i + 1) / (n_template + 1)) for i in range(n_template)]
    template_sum = None
    for idx, t in enumerate(frames):
        print(f"  Reading template frame {idx+1}/{n_template} → t={t}")

        mem = read_reg_tiff(mem_dir, t, 1)       
        ca  = read_reg_tiff(ca_dir,  t, 0)
        ref = read_reg_tiff(ref_dir, t, 'ref')
        cor = compute_cor_fn(mem, ca)  

        # 累加
        if template_sum is None:
            template_sum = cor.astype(cp.float32)
        else:
            template_sum += cor

    # get template
    template = cp.asarray(template_sum / n_template)  # (Z,Y,X)

    print("Computing spatial mask …")

    # compute gradient amplitude
    Iamp = gradient_amplitude(template)
    Iamp_mu = cp.median(Iamp)
    Iamp_sigma = cp.std(Iamp) + 1e-6
    Iz = (Iamp - Iamp_mu) / Iamp_sigma

    # smooth
    L = option["sigma"] * 2 + 1
    Iz_sm = cupy_ndimage.gaussian_filter(Iz, sigma=L)

    # intensity mask 
    dat_intMask = cupy_ndimage.median_filter(
        template < cp.median(template),
        size=(3, 3, 1)
    )
    # spatial structure mask
    dat_spatialMask = cupy_ndimage.median_filter(
        Iz_sm < option["spatialMaskThres"],
        size=(option["sigma"] * 3 + 1,
              option["sigma"] * 3 + 1,
              1)
    )
    spatialMask = (dat_spatialMask | dat_intMask).astype(cp.bool_)

    os.makedirs(out_dir, exist_ok=True)

    spatial_np = cp.asnumpy(spatialMask.astype(cp.uint8))

    write_volume_as_ome_tiff(
        spatial_np,
        out_dir=out_dir,
        ch_idx='SpatialMask',
        frame_idx=0,
        configPath=configPath
    )

    print(f"Spatial mask written to {out_dir}")

    return spatialMask

def compute_temporal_and_accumula_masks(
    mem_dir,
    ca_dir,
    ref_dir,
    out_temporal_dir,
    out_accumula_dir,
    T,
    compute_cor_fn,
    option,
    configPath,
    read_reg_tiff,
    write_volume_as_ome_tiff
):
    """
    Compute temporal masks and accumulative masks in a fully streaming manner.

    This function processes the dataset frame-by-frame and generates two types
    of masks:
        1. Temporal mask:
            Identifies short-term transient changes by computing a z-score
            over a sliding window of the most recent `n` frames.
        2. Accumulative mask:
            Tracks persistent or long-term signal changes using a separate
            window of size `n3`, combined with an accumulation threshold `n2`.

    The entire workflow is streaming-based:
        - All temporal statistics (mean, std, past masks) are maintained in
          memory using ring buffers.
        - No past masks are reloaded from disk.
        - Each newly generated mask is saved as a single-frame OME-TIFF.

    Parameters
    ----------
    mem_dir : str
        Directory containing the registered membrane channel.
    ca_dir : str
        Directory containing the registered calcium channel.
    ref_dir : str
        Directory containing the registered reference channel.
    out_temporal_dir : str
        Output directory for temporal masks.
    out_accumula_dir : str
        Output directory for accumulative masks.
    T : int
        Total number of frames to process.
    compute_cor_fn : callable
        User-supplied function computing correlation volume:
            cor = compute_cor_fn(mem, ca)
        Must return a CuPy array of shape (Z, Y, X).
    option : dict
        Parameter dictionary containing:
            'sigma2' : float
                Gaussian smoothing standard deviation for difference volume.
            'temporalMaskThres' : float
                Z-score threshold for temporal mask.
            'n' : int
                Size of ring buffer for temporal z-score statistics.
            'n2' : int
                Threshold for accumulative mask activation.
            'n3' : int
                Size of buffer for long-term accumulation.
    configPath : str
        Path to the pipeline configuration file.
    read_reg_tiff : callable
        Function to read a single registered frame:
            vol = read_reg_tiff(path, frame_index, channel)
        Returns a CuPy or NumPy array of shape (Z, Y, X).
    write_volume_as_ome_tiff : callable
        Function to save a 3D volume as an OME-TIFF file.

    Notes
    -----
    - `diff_buffer` tracks the last `n` smoothed difference volumes for
      computing temporal z-scores.
    - `temporal_buffer` tracks the last `n3` binary temporal masks for
      long-term accumulation.
    - `distCnt` maintains cumulative temporal activity counts.
    - `accum_prev` keeps previously computed accumulative mask to ensure
      monotonic growth.

    Returns
    -------
    None
        All outputs are written directly to disk during processing.
    """

    sigma2 = option["sigma2"]
    temporalTh = option["temporalMaskThres"]

    n  = option["n"]
    n2 = option["n2"]
    n3 = option["n3"]

    diff_buffer = None  #  (n, Z, Y, X)
    temporal_buffer = None  #(n3, Z, Y, X)
    distCnt = None
    accum_prev = None

    for t in range(T):

        if t % 100 == 0:
            print("Processed", t)
        mem = read_reg_tiff(mem_dir, t, 1)       
        ca  = read_reg_tiff(ca_dir,  t, 0)
        ref = cp.asarray(read_reg_tiff(ref_dir, t, 'ref'))
        cor = cp.asarray(compute_cor_fn(mem, ca))
        dif = cp.abs(cor - ref)
        dif = cupy_ndimage.gaussian_filter(dif, sigma=sigma2)
        if diff_buffer is None:
            diff_buffer = cp.zeros((n,) + dif.shape, dtype=cp.float32)
            temporal_buffer = cp.zeros((n3,) + dif.shape, dtype=cp.bool_)
            distCnt = cp.zeros(dif.shape, dtype=cp.int32)
            accum_prev = cp.zeros(dif.shape, dtype=cp.bool_)
        if t < n:
            diff_buffer[t % n] = dif
            write_volume_as_ome_tiff(np.zeros_like(cp.asnumpy(dif)), out_temporal_dir, 'TemporalMask',t, configPath)
            write_volume_as_ome_tiff(np.zeros_like(cp.asnumpy(dif)), out_accumula_dir,'AccumulaMask' ,t, configPath)
            continue

        diff_mu = cp.mean(diff_buffer, axis=0)
        diff_sigma = cp.std(diff_buffer, axis=0) + 1e-6
        dat_z = (dif - diff_mu) / diff_sigma

        temporalMask = (dat_z > temporalTh)
        write_volume_as_ome_tiff(cp.asnumpy(temporalMask).astype(np.uint8), out_temporal_dir, 'TemporalMask',t, configPath)

        distCnt += temporalMask
        if t >= n3:
            old_idx = t % n3
            distCnt -= temporal_buffer[old_idx]
        temporal_buffer[t % n3] = temporalMask

        accumulaMask = (accum_prev | (distCnt > n2))
        accum_prev = accumulaMask
        write_volume_as_ome_tiff(cp.asnumpy(accumulaMask).astype(np.uint8), out_accumula_dir,'AccumulaMask' , t, configPath)
        diff_buffer[t % n] = dif

    print("Finished computing temporal & accumulative masks.")

