# reliablemask.py
from . import cp
from . import cupy_ndimage

def write_multichannel_volume_as_ome_tiff(vol3d_list, out_dir, frame_idx, configPath,
                                          spacing_x=1.0, spacing_y=1.0):
    """
    vol3d_list: list of 3 arrays, each (Z,Y,X)
        ch0, ch1, ch2

    output OME TIFF shape: (1, Z, 3, Y, X)
    """

    assert len(vol3d_list) == 3, "vol3d_list must contain exactly 3 volumes."

    processed = []
    for v in vol3d_list:
        if v.ndim == 2:
            v = v[np.newaxis, :, :]
        if v.dtype == bool:
            v = v.astype(np.uint8)
        elif v.dtype not in [np.uint8, np.float32]:
            v = v.astype(np.float32)
        processed.append(v)

    Z, Y, X = processed[0].shape
    img5d = np.stack(processed, axis=0)     # (3, Z, Y, X)
    img5d = img5d[np.newaxis, :, :, :, :]   # (1,3,Z,Y,X)
    img5d = np.transpose(img5d, (0, 2, 1, 3, 4))  # → (1,Z,3,Y,X)

    fname = os.path.join(out_dir, f"vol_{frame_idx:06d}_masked.tif")

    metadata = {
        'spacing_x': spacing_x,
        'spacing_y': spacing_y,
        'data_shape': img5d.shape
    }

    IO.saveTiff_new(
        img5d,
        fname,
        config_path=configPath,
        metadata=metadata,
        verbose=False
    )
def gradient_amplitude(volume: cp.ndarray) -> cp.ndarray:
    """
    Compute gradient amplitude of a 2D/3D image.
    volume: shape = (X,Y) or (X,Y,Z)
    """
    if volume.ndim == 2:  # 2D
        gx = cupy_ndimage.sobel(volume, axis=0)
        gy = cupy_ndimage.sobel(volume, axis=1)
        return cp.sqrt(gx**2 + gy**2)
    elif volume.ndim == 3:  # 3D
        gx = cupy_ndimage.sobel(volume, axis=0)
        gy = cupy_ndimage.sobel(volume, axis=1)
        gz = cupy_ndimage.sobel(volume, axis=2)
        return cp.sqrt(gx**2 + gy**2 + gz**2)
    else:
        raise ValueError("Only 2D or 3D data are supported")


def compute_spatial_mask(
    mem_dir: str,
    ca_dir: str,
    ref_dir: str,
    option: dict,
    compute_cor_fn,
    read_reg_tiff,
    write_volume_as_ome_tiff,
    configPath: str,
    out_dir: str,
    T: int,
):
    """
    Compute a spatial mask based on membrane / calcium / reference signals.

    This function builds a spatial template by sampling a number of frames
    uniformly across the full time series. The template is generated by averaging
    correlation volumes computed from (membrane, calcium) pairs. The spatial mask
    is then derived by combining:
        - intensity-based masking (low-intensity structures),
        - gradient-structure-based masking (low spatial gradients).

    The final mask is saved as a single-frame OME-TIFF volume.

    Parameters
    ----------
    mem_dir : str
        Path to the registered membrane data directory.
    ca_dir : str
        Path to the registered calcium data directory.
    ref_dir : str
        Path to the registered reference data directory.
    option : dict
        Dictionary containing parameters:
            'sigma': int
                Smoothing scale for gradient-based features.
            'spatialMaskThres': float
                Threshold for the standardized gradient field (Iz_sm).
    compute_cor_fn : callable
        User-provided function that computes correlation:
            cor = compute_cor_fn(mem, ca)
        where the output shape must be (Z, Y, X).
    read_reg_tiff : callable
        Function for reading one frame:
            vol = read_reg_tiff(dir, frame_index, channel)
        Must return a CuPy array with shape (Z, Y, X).
    write_volume_as_ome_tiff : callable
        Function for writing a 3D volume into an OME-TIFF file.
    configPath : str
        Path to the pipeline configuration file.
    out_dir : str
        Directory to store the output spatial mask.
    T : int
        Total number of frames in the dataset.

    Returns
    -------
    spatialMask : cupy.ndarray, dtype=bool, shape=(Z, Y, X)
        The computed spatial mask.
    """
      
    print("Pass 1: building spatial template")

    n_template = min(20, T)
    frames = [int(T * (i + 1) / (n_template + 1)) for i in range(n_template)]
    template_sum = None
    for idx, t in enumerate(frames):
        print(f"  Reading template frame {idx+1}/{n_template} → t={t}")

        mem = read_reg_tiff(mem_dir, t, 1)       
        ca  = read_reg_tiff(ca_dir,  t, 0)
        ref = read_reg_tiff(ref_dir, t, 'ref')
        cor = compute_cor_fn(mem, ca)  

        # 累加
        if template_sum is None:
            template_sum = cor.astype(cp.float32)
        else:
            template_sum += cor

    # get template
    template = cp.asarray(template_sum / n_template)  # (Z,Y,X)

    print("Computing spatial mask …")

    # compute gradient amplitude
    Iamp = gradient_amplitude(template)
    Iamp_mu = cp.median(Iamp)
    Iamp_sigma = cp.std(Iamp) + 1e-6
    Iz = (Iamp - Iamp_mu) / Iamp_sigma

    # smooth
    L = option["sigma"] * 2 + 1
    Iz_sm = cupy_ndimage.gaussian_filter(Iz, sigma=L)

    # intensity mask 
    dat_intMask = cupy_ndimage.median_filter(
        template < cp.median(template),
        size=(3, 3, 1)
    )
    # spatial structure mask
    dat_spatialMask = cupy_ndimage.median_filter(
        Iz_sm < option["spatialMaskThres"],
        size=(option["sigma"] * 3 + 1,
              option["sigma"] * 3 + 1,
              1)
    )
    spatialMask = (dat_spatialMask | dat_intMask).astype(cp.bool_)

    os.makedirs(out_dir, exist_ok=True)

    spatial_np = cp.asnumpy(spatialMask.astype(cp.uint8))

    write_volume_as_ome_tiff(
        spatial_np,
        out_dir=out_dir,
        ch_idx='SpatialMask',
        frame_idx=0,
        configPath=configPath
    )

    print(f"Spatial mask written to {out_dir}")

    return spatialMask

def compute_temporal_and_accumula_masks(
    mem_dir,
    ca_dir,
    ref_dir,
    out_temporal_dir,
    out_accumula_dir,
    T,
    compute_cor_fn,
    option,
    configPath,
    read_reg_tiff,
    write_volume_as_ome_tiff
):
    """
    Compute temporal masks and accumulative masks in a fully streaming manner.

    This function processes the dataset frame-by-frame and generates two types
    of masks:
        1. Temporal mask:
            Identifies short-term transient changes by computing a z-score
            over a sliding window of the most recent `n` frames.
        2. Accumulative mask:
            Tracks persistent or long-term signal changes using a separate
            window of size `n3`, combined with an accumulation threshold `n2`.

    The entire workflow is streaming-based:
        - All temporal statistics (mean, std, past masks) are maintained in
          memory using ring buffers.
        - No past masks are reloaded from disk.
        - Each newly generated mask is saved as a single-frame OME-TIFF.

    Parameters
    ----------
    mem_dir : str
        Directory containing the registered membrane channel.
    ca_dir : str
        Directory containing the registered calcium channel.
    ref_dir : str
        Directory containing the registered reference channel.
    out_temporal_dir : str
        Output directory for temporal masks.
    out_accumula_dir : str
        Output directory for accumulative masks.
    T : int
        Total number of frames to process.
    compute_cor_fn : callable
        User-supplied function computing correlation volume:
            cor = compute_cor_fn(mem, ca)
        Must return a CuPy array of shape (Z, Y, X).
    option : dict
        Parameter dictionary containing:
            'sigma2' : float
                Gaussian smoothing standard deviation for difference volume.
            'temporalMaskThres' : float
                Z-score threshold for temporal mask.
            'n' : int
                Size of ring buffer for temporal z-score statistics.
            'n2' : int
                Threshold for accumulative mask activation.
            'n3' : int
                Size of buffer for long-term accumulation.
    configPath : str
        Path to the pipeline configuration file.
    read_reg_tiff : callable
        Function to read a single registered frame:
            vol = read_reg_tiff(path, frame_index, channel)
        Returns a CuPy or NumPy array of shape (Z, Y, X).
    write_volume_as_ome_tiff : callable
        Function to save a 3D volume as an OME-TIFF file.

    Notes
    -----
    - `diff_buffer` tracks the last `n` smoothed difference volumes for
      computing temporal z-scores.
    - `temporal_buffer` tracks the last `n3` binary temporal masks for
      long-term accumulation.
    - `distCnt` maintains cumulative temporal activity counts.
    - `accum_prev` keeps previously computed accumulative mask to ensure
      monotonic growth.

    Returns
    -------
    None
        All outputs are written directly to disk during processing.
    """

    sigma2 = option["sigma2"]
    temporalTh = option["temporalMaskThres"]

    n  = option["n"]
    n2 = option["n2"]
    n3 = option["n3"]

    diff_buffer = None  #  (n, Z, Y, X)
    temporal_buffer = None  #(n3, Z, Y, X)
    distCnt = None
    accum_prev = None

    for t in range(T):

        if t % 100 == 0:
            print("Processed", t)
        mem = read_reg_tiff(mem_dir, t, 1)       
        ca  = read_reg_tiff(ca_dir,  t, 0)
        ref = cp.asarray(read_reg_tiff(ref_dir, t, 'ref'))
        cor = cp.asarray(compute_cor_fn(mem, ca))
        dif = cp.abs(cor - ref)
        dif = cupy_ndimage.gaussian_filter(dif, sigma=sigma2)
        if diff_buffer is None:
            diff_buffer = cp.zeros((n,) + dif.shape, dtype=cp.float32)
            temporal_buffer = cp.zeros((n3,) + dif.shape, dtype=cp.bool_)
            distCnt = cp.zeros(dif.shape, dtype=cp.int32)
            accum_prev = cp.zeros(dif.shape, dtype=cp.bool_)
        if t < n:
            diff_buffer[t % n] = dif
            write_volume_as_ome_tiff(np.zeros_like(cp.asnumpy(dif)), out_temporal_dir, 'TemporalMask',t, configPath)
            write_volume_as_ome_tiff(np.zeros_like(cp.asnumpy(dif)), out_accumula_dir,'AccumulaMask' ,t, configPath)
            continue

        diff_mu = cp.mean(diff_buffer, axis=0)
        diff_sigma = cp.std(diff_buffer, axis=0) + 1e-6
        dat_z = (dif - diff_mu) / diff_sigma

        temporalMask = (dat_z > temporalTh)
        write_volume_as_ome_tiff(cp.asnumpy(temporalMask).astype(np.uint8), out_temporal_dir, 'TemporalMask',t, configPath)

        distCnt += temporalMask
        if t >= n3:
            old_idx = t % n3
            distCnt -= temporal_buffer[old_idx]
        temporal_buffer[t % n3] = temporalMask

        accumulaMask = (accum_prev | (distCnt > n2))
        accum_prev = accumulaMask
        write_volume_as_ome_tiff(cp.asnumpy(accumulaMask).astype(np.uint8), out_accumula_dir,'AccumulaMask' , t, configPath)
        diff_buffer[t % n] = dif

    print("Finished computing temporal & accumulative masks.")

def compute_temporal_and_accumula_masks_v2(
    mem_dir,
    ca_dir,
    ref_dir,
    spatial_mask,
    T,
    compute_cor_fn,
    option,
    configPath,
    read_reg_tiff
):
    """
    Compute temporal masks and accumulative masks in a fully streaming manner.

    This function processes the dataset frame-by-frame and generates two types
    of masks:
        1. Temporal mask:
            Identifies short-term transient changes by computing a z-score
            over a sliding window of the most recent `n` frames.
        2. Accumulative mask:
            Tracks persistent or long-term signal changes using a separate
            window of size `n3`, combined with an accumulation threshold `n2`.

    The entire workflow is streaming-based:
        - All temporal statistics (mean, std, past masks) are maintained in
          memory using ring buffers.
        - No past masks are reloaded from disk.
        - Each newly generated mask is saved as a single-frame OME-TIFF.

    Parameters
    ----------
    mem_dir : str
        Directory containing the registered membrane channel.
    ca_dir : str
        Directory containing the registered calcium channel.
    ref_dir : str
        Directory containing the registered reference channel.
    out_temporal_dir : str
        Output directory for temporal masks.
    out_accumula_dir : str
        Output directory for accumulative masks.
    T : int
        Total number of frames to process.
    compute_cor_fn : callable
        User-supplied function computing correlation volume:
            cor = compute_cor_fn(mem, ca)
        Must return a CuPy array of shape (Z, Y, X).
    option : dict
        Parameter dictionary containing:
            'sigma2' : float
                Gaussian smoothing standard deviation for difference volume.
            'temporalMaskThres' : float
                Z-score threshold for temporal mask.
            'n' : int
                Size of ring buffer for temporal z-score statistics.
            'n2' : int
                Threshold for accumulative mask activation.
            'n3' : int
                Size of buffer for long-term accumulation.
    configPath : str
        Path to the pipeline configuration file.
    read_reg_tiff : callable
        Function to read a single registered frame:
            vol = read_reg_tiff(path, frame_index, channel)
        Returns a CuPy or NumPy array of shape (Z, Y, X).
    write_volume_as_ome_tiff : callable
        Function to save a 3D volume as an OME-TIFF file.

    Notes
    -----
    - `diff_buffer` tracks the last `n` smoothed difference volumes for
      computing temporal z-scores.
    - `temporal_buffer` tracks the last `n3` binary temporal masks for
      long-term accumulation.
    - `distCnt` maintains cumulative temporal activity counts.
    - `accum_prev` keeps previously computed accumulative mask to ensure
      monotonic growth.

    Returns
    -------
    None
        All outputs are written directly to disk during processing.
    """

    sigma2 = option["sigma2"]
    temporalTh = option["temporalMaskThres"]

    n  = option["n"]
    n2 = option["n2"]
    n3 = option["n3"]

    diff_buffer = None  #  (n, Z, Y, X)
    temporal_buffer = None  #(n3, Z, Y, X)
    distCnt = None
    accum_prev = None
    import toml
    config=toml.load(configPath)
    for t in range(T):
        if t % 100 == 0:
            print("Processed", t)
        mem = read_reg_tiff(mem_dir, t, 1)       
        ca  = read_reg_tiff(ca_dir,  t, 0)
        ref = cp.asarray(read_reg_tiff(ref_dir, t, 'ref'))
        cor = cp.asarray(compute_cor_fn(mem, ca))
        dif = cp.abs(cor - ref)
        dif = cupy_ndimage.gaussian_filter(dif, sigma=sigma2)
        if diff_buffer is None:
            diff_buffer = cp.zeros((n,)  + dif.shape, dtype=cp.float32)
            temporal_buffer = cp.zeros((n3,) + dif.shape, dtype=cp.bool_)
            distCnt = cp.zeros(dif.shape, dtype=cp.int32)
            accum_prev = cp.zeros(dif.shape, dtype=cp.bool_)

        if t < n:
            diff_buffer[t % n] = dif
            mask_final = spatial_mask 
        else:
            diff_mu = cp.mean(diff_buffer, axis=0)
            diff_sigma = cp.std(diff_buffer, axis=0) + 1e-6
            dat_z = (dif - diff_mu) / diff_sigma

            temporalMask = (dat_z > temporalTh)

            distCnt += temporalMask
            if t >= n3:
                old_idx = t % n3
                distCnt -= temporal_buffer[old_idx]

            temporal_buffer[t % n3] = temporalMask

            accumulaMask = (accum_prev | (distCnt > n2))
            accum_prev = accumulaMask

            mask_final = (spatial_mask | temporalMask | accumulaMask)

            diff_buffer[t % n] = dif

        mask_final_cpu = cp.asnumpy(mask_final)
        mem_cpu = cp.asnumpy(mem)
        masked_cpu = mem_cpu * (1-mask_final_cpu)
        

        write_multichannel_volume_as_ome_tiff(
            [mem_cpu, masked_cpu, mask_final_cpu.astype(np.uint8)],
            out_dir=config['file_path']['mask_path'],
            frame_idx=t,
            configPath=configPath
        )


    print("Finished computing temporal & accumulative masks.")

####################################################################################################################

## 2024/12/8 update
## change the mask to a float format
##

from skimage.metrics import structural_similarity  as ssim
from scipy.ndimage import gaussian_filter

def local_ssim_difference(I_ref,I_mov,win_size=11,use_3d=False,sigma_3d=1.5):
    """
    Compute local SSIM difference map (0~1) between two images.
    Supports 2D and 3D images. 
    
    Parameters
    ----------
    I_ref : np.ndarray
        Reference image (2D or 3D).
    I_mov : np.ndarray
        Registered/moving image (must match shape of I_ref).
    win_size : int
        SSIM window size for 2D (odd number like 11, 21).
    use_3d : bool
        If True, compute a true 3D SSIM approximation using Gaussian smoothing.
        If False, compute 2D SSIM slice-by-slice for 3D volumes (recommended for microscopy).
    sigma_3d : float or tuple
        Gaussian sigma used in 3D SSIM approximation mode.

    Returns
    -------
    D : np.ndarray, float32
        Difference map in [0,1], same shape as input.
    """
    I_ref=I_ref.astype(np.float32)
    I_mov=I_mov.astype(np.float32)
    
    if I_ref.ndim not in [2, 3]:
        raise ValueError("Input images must be 2D or 3D numpy arrays.")
    
    if I_ref.shape != I_mov.shape:
        raise ValueError("Input images must have the same shape.")
    # -----------------------
    # Case 1: 2D Image
    # -----------------------
    if I_ref.ndim == 2:
        _, ssim_map = ssim(
            I_ref, I_mov,
            win_size=win_size,
            gaussian_weights=True,
            data_range=I_ref.max() - I_ref.min(),
            full=True
        )
        D = (1 - ssim_map) / 2.0
        return np.clip(D.astype(np.float32), 0, 1)

    # -----------------------
    # Case 2: 3D Image
    # -----------------------
    if not use_3d:
        # --- Slice-wise 2D SSIM (recommended for microscopy with low Z-resolution)
        Z = I_ref.shape[0]
        D = np.zeros_like(I_ref, dtype=np.float32)

        for z in range(Z):
            _, ssim_map = ssim(
                I_ref[z], I_mov[z],
                win_size=win_size,
                gaussian_weights=True,
                data_range=I_ref[z].max() - I_ref[z].min(),
                full=True
            )
            D[z] = (1 - ssim_map) / 2.0
        
        return np.clip(D, 0, 1)

    else:
        # --- True 3D SSIM approximation using Gaussian filters
        #     (Useful only if Z-resolution is comparable to XY)
        
        C1 = (0.01 * (I_ref.max() - I_ref.min())) ** 2
        C2 = (0.03 * (I_ref.max() - I_ref.min())) ** 2

        mu_x = gaussian_filter(I_ref, sigma=sigma_3d)
        mu_y = gaussian_filter(I_mov, sigma=sigma_3d)

        mu_x2 = mu_x * mu_x
        mu_y2 = mu_y * mu_y
        mu_xy = mu_x * mu_y

        sigma_x2 = gaussian_filter(I_ref * I_ref, sigma=sigma_3d) - mu_x2
        sigma_y2 = gaussian_filter(I_mov * I_mov, sigma=sigma_3d) - mu_y2
        sigma_xy = gaussian_filter(I_ref * I_mov, sigma=sigma_3d) - mu_xy

        numerator = (2 * mu_xy + C1) * (2 * sigma_xy + C2)
        denominator = (mu_x2 + mu_y2 + C1) * (sigma_x2 + sigma_y2 + C2)

        ssim_map = numerator / (denominator + 1e-12)
        D = (1 - ssim_map) / 2

        return np.clip(D.astype(np.float32), 0, 1)
    
def build_reference_index(ref_dir):
    """
    scan reference folder, construct frame -> filepath
    return:
        ref_map: dict(frame -> filepath)
        ref_files: list of all files
    """
    ref_files = [f for f in os.listdir(ref_dir) if f.endswith(".tif")]
    ref_map = {}

    for f in ref_files:
        m_multi = re.match(r"vol_chref_(\d{6})_(\d{6})\.tif", f)
        m_single = re.match(r"vol_chref_(\d{6})\.tif", f)

        if m_multi:
            a = int(m_multi.group(1))
            b = int(m_multi.group(2))
            for t in range(a, b + 1):
                ref_map[t] = os.path.join(ref_dir, f)

        elif m_single:
            a = int(m_single.group(1))
            ref_map[a] = os.path.join(ref_dir, f)

        else:
            print(f"[WARNING] Unknown reference filename format: {f}")

    return ref_map, ref_files


def ComputMask(
                mem_dir,
                ca_dir,
                ref_dir,
                out_dir,
                config,
                compute_cor_fn,
                configPath,
                T,
                downsampleXY=1,
                downsampleT=1
):
    def overlay_ssim_map(ssim_map, img, alpha=0.5, gamma=0.3):
        import numpy as np
        import cv2

        def process_slice(ssim_slice, img_slice):
            diff = 1 - ssim_slice
            diff_norm = (diff - diff.min()) / (diff.max() - diff.min() + 1e-8)
            diff_enhanced = diff_norm ** gamma
            img_norm = (img_slice - img_slice.min()) / (img_slice.max() - img_slice.min() + 1e-8)

            heat = cv2.applyColorMap((diff_enhanced * 255).astype(np.uint8), cv2.COLORMAP_JET)
            heat = heat[..., ::-1] / 255.0  # BGR → RGB

            img_rgb = np.stack([img_norm]*3, axis=-1)

            overlay = (1 - alpha) * img_rgb + alpha * heat
            return overlay  # (H, W, 3)
        if ssim_map.ndim == 2:
            overlay = process_slice(ssim_map, img)
            return overlay.transpose(2,0,1)[None]   
        overlays = []
        for z in range(ssim_map.shape[0]):
            overlays.append(process_slice(ssim_map[z], img[z]))
        overlays = np.array(overlays)      
        overlays = overlays.transpose(3,0,1,2)
        return overlays
    mask_dir=os.path.join(out_dir,'mask')
    overlay_dir=os.path.join(out_dir,'overlay')
    os.makedirs(mask_dir,exist_ok=True)
    os.makedirs(overlay_dir,exist_ok=True)
    ref_map,ref_files=build_reference_index(ref_dir)
    for i in range(T):
        if i % 100 == 0:
            print("Processed", i)
        mem_i=IO.read_reg_tiff(mem_dir,i,1)
        ca_i=IO.read_reg_tiff(ca_dir,i,0)
        cor_i=compute_cor_fn(mem_i,ca_i)
        ref_i=tifffile.imread(ref_map[i])

        win_size=config['win_size']
        use_3d=config['use_3d']
        sigma_3d=config['sigma_3d']
        mask_map=local_ssim_difference(cor_i,ref_i,win_size,use_3d,sigma_3d)
        image_list=[ref_i,cor_i,mask_map]
        IO.write_multichannel_volume_as_ome_tiff(image_list,os.path.join(out_dir,'mask'),
                                                 i,configPath,'mask')
        if i % downsampleT == 0:
            image_list_ds=[
                            np.squeeze(
                                IO.downsample(
                                    np.expand_dims(np.expand_dims(ref_i, axis=1), axis=0),
                                    downsampleXY)
                                    ),
                            np.squeeze(
                                IO.downsample(
                                    np.expand_dims(np.expand_dims(cor_i, axis=1), axis=0),
                                    downsampleXY)
                                    ),
                            np.squeeze(
                                IO.downsample(
                                    np.expand_dims(np.expand_dims(mask_map, axis=1), axis=0),
                                    downsampleXY)
                                    )
                           ]
            IO.write_multichannel_volume_as_ome_tiff(image_list_ds,mask_ds_dir,
                                                 i,configPath,'mask')
